# Generated by Django 5.0.6 on 2024-05-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='rent2week',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rentmonth',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='rentweek',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
