# Generated by Django 5.0.6 on 2024-05-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_rent_product_rent2week_product_rentmonth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rent2week',
            new_name='rent_per_month',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='rentmonth',
            new_name='rent_per_week',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rentweek',
        ),
    ]
